\c banking_data

INSERT INTO customers (name, email, city) VALUES
('Alice Johnson', 'alice1@example.com', 'Toronto'),
('Bob Smith', 'bob2@example.com', 'Vancouver'),
('Charlie Brown', 'charlie3@example.com', 'Montreal'),
('David Lee', 'david4@example.com', 'Calgary'),
('Eva Green', 'eva5@example.com', 'Ottawa'),
('Frank White', 'frank6@example.com', 'Edmonton'),
('Grace Kim', 'grace7@example.com', 'Winnipeg'),
('Hannah Scott', 'hannah8@example.com', 'Halifax'),
('Ian Turner', 'ian9@example.com', 'Quebec City'),
('Jackie Chan', 'jackie10@example.com', 'Mississauga'),
('Karen Hill', 'karen11@example.com', 'Toronto'),
('Leo King', 'leo12@example.com', 'Vancouver'),
('Mia Moore', 'mia13@example.com', 'Montreal'),
('Nina Young', 'nina14@example.com', 'Calgary'),
('Oscar Reed', 'oscar15@example.com', 'Ottawa'),
('Paula Fox', 'paula16@example.com', 'Edmonton'),
('Quincy Adams', 'quincy17@example.com', 'Winnipeg'),
('Rita Hall', 'rita18@example.com', 'Halifax'),
('Sam Patel', 'sam19@example.com', 'Quebec City'),
('Tina Evans', 'tina20@example.com', 'Mississauga'),
('Uma Shah', 'uma21@example.com', 'Toronto'),
('Victor Li', 'victor22@example.com', 'Vancouver'),
('Wendy Zhao', 'wendy23@example.com', 'Montreal'),
('Xavier Cruz', 'xavier24@example.com', 'Calgary'),
('Yara Khan', 'yara25@example.com', 'Ottawa'),
('Zane Cole', 'zane26@example.com', 'Edmonton'),
('Aaron Black', 'aaron27@example.com', 'Winnipeg'),
('Bella Wright', 'bella28@example.com', 'Halifax'),
('Caleb Diaz', 'caleb29@example.com', 'Quebec City'),
('Diana Bell', 'diana30@example.com', 'Mississauga'),
('Ethan Fox', 'ethan31@example.com', 'Toronto'),
('Fiona Ross', 'fiona32@example.com', 'Vancouver'),
('George Hill', 'george33@example.com', 'Montreal'),
('Holly Green', 'holly34@example.com', 'Calgary'),
('Isaac King', 'isaac35@example.com', 'Ottawa'),
('Julia Lee', 'julia36@example.com', 'Edmonton'),
('Kevin Brown', 'kevin37@example.com', 'Winnipeg'),
('Laura Smith', 'laura38@example.com', 'Halifax'),
('Mike Johnson', 'mike39@example.com', 'Quebec City'),
('Nora Adams', 'nora40@example.com', 'Mississauga'),
('Owen Clark', 'owen41@example.com', 'Toronto'),
('Paige Martin', 'paige42@example.com', 'Vancouver'),
('Quinn Davis', 'quinn43@example.com', 'Montreal'),
('Rachel Moore', 'rachel44@example.com', 'Calgary'),
('Steve White', 'steve45@example.com', 'Ottawa'),
('Tara Hill', 'tara46@example.com', 'Edmonton'),
('Ulysses King', 'ulysses47@example.com', 'Winnipeg'),
('Vera Scott', 'vera48@example.com', 'Halifax'),
('William Lee', 'william49@example.com', 'Quebec City'),
('Xena Zhao', 'xena50@example.com', 'Mississauga');

SELECT * FROM customers;
